"""create user table

Revision ID: bf6b93edced3
Revises: 60fd1bea70ea
Create Date: 2025-05-10 14:24:57.234899

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "bf6b93edced3"
down_revision: Union[str, None] = "60fd1bea70ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
